name: "Build and test"
on:
  push:
  pull_request:
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: configure
        run: cmake -S . -B build
      - name: build
        run: cmake --build build -j
      - name: test
        run: ./build/address_book_tests
      
